### ISSUE TITLE
Fail to build on Mac OS X

### ISSUE THREAD

**Issue by abailly** [rrthomas/bee#18]
I am trying to build `bee` from source on Mac OS X (Monterey 12.2.1) using `./bootstrap` and get the following failure:
```
Don't forget to
  - add "lib/Makefile" to AC_CONFIG_FILES in ./configure.ac,
  - mention "lib" in SUBDIRS in Makefile.am,
  - mention "-I m4" in ACLOCAL_AMFLAGS in Makefile.am,
  - mention "m4/gnulib-cache.m4" in EXTRA_DIST in Makefile.am,
  - invoke gl_EARLY in ./configure.ac, right after AC_PROG_CC_C99,
  - invoke gl_INIT in ./configure.ac.
bootstrap: running: autoreconf --symlink --install
/Library/Developer/CommandLineTools/usr/bin/gm4: unrecognized option `--gnu'
Try `/Library/Developer/CommandLineTools/usr/bin/gm4 --help' for more information.
autom4te: error: /usr/bin/gm4 failed with exit status: 1
aclocal: error: autom4te failed with exit status: 1
autoreconf: error: aclocal failed with exit status: 1
```

I can build the distribution tarball fine.

**Comment by rrthomas** [comment]
Unfortunately, macOS's GNU m4 is too old. I have added a version requirement to `bootstrap.conf` that should now give a better error message.

**Comment by abailly** [comment]
Thanks a lot! I guess I can override with brew's version?

**Comment by rrthomas** [comment]
Exactly! `bootstrap` should find it provided it's somewhere on your `PATH` (doesn't even have to be before the system version).

**Comment by abailly** [comment]
Actually, it was there but I have had to prepend `PATH` 🤷
